In [3]:
import pandas as pd

In [4]:
df = pd.read_csv(
"../outputs/cleaned_data/featured_dataset.csv"
)

C:\Users\sushi\AppData\Local\Temp\ipykernel_8172\66973893.py:1: DtypeWarning: Columns (0: product_width_cm) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(

In [5]:
kpi = {

"Total Revenue":
df["payment_value"].sum(),

"Total Orders":
df["order_id"].nunique(),

"Total Customers":
df["customer_unique_id"].nunique(),

"Total Products":
df["product_id"].nunique(),

"Average Order Value":
round(df["payment_value"].mean(),2),

"Average Delivery Days":
round(df["delivery_days"].mean(),2),

"Average Rating":
round(df["review_score"].mean(),2)

}

In [6]:
kpi_df = pd.DataFrame(

kpi.items(),

columns=[

"KPI",

"Value"

]

)

kpi_df

                     KPI        Value
0          Total Revenue  20579664.01
1           Total Orders     99441.00
2        Total Customers     96096.00
3         Total Products     32951.00
4    Average Order Value       172.74
5  Average Delivery Days        12.02
6         Average Rating         4.02

In [7]:
kpi_df.to_csv(

"../outputs/reports/kpi_summary.csv",

index=False

)

In [8]:
summary = {

"Top State":

df.groupby(

"customer_state"

)["payment_value"]

.sum()

.idxmax(),

"Top Category":

df.groupby(

"product_category_name_english"

)["payment_value"]

.sum()

.idxmax(),

"Top Seller":

df.groupby(

"seller_id"

)["payment_value"]

.sum()

.idxmax(),

"Most Used Payment":

df["payment_type"]

.mode()[0]

}

In [9]:
summary_df = pd.DataFrame(

summary.items(),

columns=[

"Metric",

"Value"

]

)

summary_df

              Metric                             Value
0          Top State                                SP
1       Top Category                  bed_bath_table\r
2         Top Seller  7c67e1448b00f6e969d365cea6b010ab
3  Most Used Payment                       credit_card

In [ ]:
summary_df.to_csv(

"../outputs/reports/business_summary.csv",

index=False

)

## Observation

Executive KPIs generated successfully.

Business Summary exported.

Ready for Dashboard Development.






isko markdown me kro